let products=[], cart=JSON.parse(localStorage.getItem("cart")||"[]"), store={currency:"MAD"};
const $=s=>document.querySelector(s);
document.addEventListener("DOMContentLoaded",async()=>{ $("#year").textContent=new Date().getFullYear(); await loadStore(); await loadProducts(); updateCartCount(); });
async function loadStore(){try{store=await fetch("/api/store").then(r=>r.json());document.querySelectorAll(".brand").forEach(x=>x.textContent=store.name);document.title=store.name;}catch{}}
async function loadProducts(){const r=await fetch("/api/products");products=await r.json();renderProducts();}
function renderProducts(){const q=($("#search")?.value||"").toLowerCase();const list=products.filter(p=>(p.name+" "+p.category).toLowerCase().includes(q));const grid=$("#productsGrid");grid.innerHTML=list.length?list.map(p=>`<article class="card"><img src="${esc(p.image_url)}" alt="${esc(p.name)}"><div class="cardBody"><div class="muted">${esc(p.category)}</div><h3>${esc(p.name)}</h3><div class="price">${Number(p.price).toFixed(2)} ${store.currency}</div><button class="btn" onclick="showProduct(${p.id})">اختيار المنتج</button></div></article>`).join(""):`<div class="empty">لا توجد منتجات مطابقة.</div>`}
function showProduct(id){const p=products.find(x=>x.id===id);if(!p)return;$("#modal").classList.remove("hidden");$("#modalContent").innerHTML=`<h2>${esc(p.name)}</h2><p class="muted">${esc(p.description)}</p><div class="row"><label>المقاس<select id="size">${(p.sizes.length?p.sizes:["اختياري"]).map(x=>`<option>${esc(x)}</option>`).join("")}</select></label><label>اللون<select id="color">${(p.colors.length?p.colors:["اختياري"]).map(x=>`<option>${esc(x)}</option>`).join("")}</select></label></div><label>الكمية<input id="qty" type="number" min="1" max="${p.stock}" value="1"></label><p class="price">${Number(p.price).toFixed(2)} ${store.currency}</p><div class="actions"><button class="btn" onclick="addToCart(${p.id})">أضف للسلة</button><button class="btn" onclick="closeModal()">إلغاء</button></div>`}
function closeModal(){$("#modal").classList.add("hidden")}
function addToCart(id){const p=products.find(x=>x.id===id),size=$("#size").value,color=$("#color").value,qty=Math.max(1,Number($("#qty").value||1));const found=cart.find(x=>x.product_id===id&&x.size===size&&x.color===color);if(found)found.quantity+=qty;else cart.push({product_id:id,name:p.name,price:Number(p.price),image_url:p.image_url,quantity:qty,size,color});saveCart();closeModal();toast("تمت إضافة المنتج للسلة");}
function saveCart(){localStorage.setItem("cart",JSON.stringify(cart));updateCartCount()}
function updateCartCount(){$("#cartCount").textContent=cart.reduce((a,x)=>a+x.quantity,0)}
function openCart(){if(!cart.length){$("#modal").classList.remove("hidden");$("#modalContent").innerHTML="<div class='empty'>السلة فارغة.</div>";return}$("#modal").classList.remove("hidden");renderCart()}
function renderCart(){const total=cart.reduce((a,x)=>a+x.price*x.quantity,0);$("#modalContent").innerHTML=`<h2>سلة المشتريات</h2>${cart.map((x,i)=>`<div class="item"><img src="${esc(x.image_url)}"><div style="flex:1"><b>${esc(x.name)}</b><div class="muted">${esc(x.size)} · ${esc(x.color)} · ${x.quantity}</div><strong>${(x.price*x.quantity).toFixed(2)} ${store.currency}</strong></div><button onclick="removeCart(${i})">حذف</button></div>`).join("")}<h3>المجموع: ${total.toFixed(2)} ${store.currency}</h3><div class="actions"><button class="btn" onclick="checkout()">إتمام الطلب</button><button class="btn" onclick="closeModal()">متابعة التسوق</button></div>`}
function removeCart(i){cart.splice(i,1);saveCart();openCart()}
function checkout(){const total=cart.reduce((a,x)=>a+x.price*x.quantity,0);$("#modalContent").innerHTML=`<h2>إتمام الطلب</h2><p class="muted">الدفع عند الاستلام.</p><form class="form" onsubmit="submitOrder(event)"><input name="customer_name" placeholder="الاسم الكامل" required><input name="phone" placeholder="رقم الهاتف" required><input name="city" placeholder="المدينة" required><textarea name="address" placeholder="العنوان بالتفصيل" required></textarea><textarea name="note" placeholder="ملاحظة (اختياري)"></textarea><p><b>المجموع: ${total.toFixed(2)} ${store.currency}</b></p><button class="btn" type="submit">تأكيد الطلب</button></form>`}
async function submitOrder(e){e.preventDefault();const f=new FormData(e.target),body=Object.fromEntries(f.entries());body.items=cart.map(x=>({product_id:x.product_id,quantity:x.quantity,size:x.size,color:x.color}));const r=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)return toast(data.error||"تعذر الطلب");cart=[];saveCart();$("#modalContent").innerHTML=`<div class="empty"><h2>تم استلام طلبك ✓</h2><p>رقم الطلب: <b>${data.order_number}</b></p><p>احتفظ برقم الطلب لتتبعه.</p><a class="btn" href="/track?order=${encodeURIComponent(data.order_number)}&phone=${encodeURIComponent(body.phone)}">تتبع الطلب</a></div>`}
function toast(t){const d=document.createElement("div");d.className="toast";d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),2500)}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
